import { Tag } from 'src/app/interfaces/tag';

export const TAG_ACADEMIA: Tag = { name: 'Academia' };
export const TAG_APPSEC: Tag = { name: 'AppSec' };
export const TAG_CLOUD: Tag = { name: 'Cloud' };
export const TAG_COMMUNITY: Tag = { name: 'Community' };
export const TAG_CONFERENCE: Tag = { name: 'Conference' };
export const TAG_CRYPTOCURRENCY: Tag = { name: 'Cryptocurrency' };
export const TAG_CRYPTOGRAPHY: Tag = { name: 'Cryptography' };
export const TAG_CTF: Tag = { name: 'CTF' };
export const TAG_CYBERSEC: Tag = { name: 'CyberSec' };
export const TAG_DEVELOPMENT: Tag = { name: 'Development' };
export const TAG_DEVOPS: Tag = { name: 'DevOps' };
export const TAG_INFOSEC: Tag = { name: 'InfoSec' };
export const TAG_IOT: Tag = { name: 'IOT' };
export const TAG_MEDIA: Tag = { name: 'Media' };
export const TAG_MOBILE: Tag = { name: 'Mobile' };
export const TAG_OSINT: Tag = { name: 'OSINT' };
export const TAG_PERSONAL: Tag = { name: 'Personal' };
export const TAG_PRIVACY: Tag = { name: 'Privacy' };
export const TAG_PROFESSIONAL: Tag = { name: 'Professional' };
export const TAG_PROGRAMMING: Tag = { name: 'Programming' };
export const TAG_REVERSE_ENGINEERING: Tag = { name: 'Reverse-Engineering' };
export const TAG_TALKS: Tag = { name: 'Talks' };
export const TAG_TRAVEL: Tag = { name: 'Travel' };
export const TAG_VOLUNTEERING: Tag = { name: 'Volunteering' };
export const TAG_WEB: Tag = { name: 'Web' };
export const TAG_WRITEUP: Tag = { name: 'Write-Up' };
